### ISSUE TITLE
non dynamic import error

### ISSUE THREAD

**Issue by KarstenSiemer** [nitzano/semantic-release-github-milestones#119]
Hi!
I'd like to try out this plugin, but it fails to execute.
What can I do about this?

```
+ semantic-release
[11:11:19 AM] [semantic-release] › ℹ  Running semantic-release version 19.0.5
[11:11:19 AM] [semantic-release] › ✖  An error occurred while running semantic-release: Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/local/lib/node_modules/semantic-release-github-milestones/node_modules/aggregate-error/index.js from /usr/local/lib/node_modules/semantic-release-github-milestones/build/verify-conditions/verify-github.js not supported.
Instead change the require of index.js in /usr/local/lib/node_modules/semantic-release-github-milestones/build/verify-conditions/verify-github.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/usr/local/lib/node_modules/semantic-release-github-milestones/build/verify-conditions/verify-github.js:44:41)
    at Object.<anonymous> (/usr/local/lib/node_modules/semantic-release-github-milestones/build/index.js:40:23)
    at loadPlugin (/usr/local/lib/node_modules/semantic-release/lib/plugins/utils.js:51:36)
    at /usr/local/lib/node_modules/semantic-release/lib/plugins/index.js:17:37
    at Array.reduce (<anonymous>)
    at module.exports (/usr/local/lib/node_modules/semantic-release/lib/plugins/index.js:14:34)
    at module.exports (/usr/local/lib/node_modules/semantic-release/lib/get-config.js:84:35)
    at async module.exports (/usr/local/lib/node_modules/semantic-release/index.js:265:32)
    at async module.exports (/usr/local/lib/node_modules/semantic-release/cli.js:55:5) {
  code: 'ERR_REQUIRE_ESM'
}
Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/local/lib/node_modules/semantic-release-github-milestones/node_modules/aggregate-error/index.js from /usr/local/lib/node_modules/semantic-release-github-milestones/build/verify-conditions/verify-github.js not supported.
Instead change the require of index.js in /usr/local/lib/node_modules/semantic-release-github-milestones/build/verify-conditions/verify-github.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/usr/local/lib/node_modules/[4msemantic-release-github-milestones[24m/build/verify-conditions/verify-github.js:44:41)
    at Object.<anonymous> (/usr/local/lib/node_modules/[4msemantic-release-github-milestones[24m/build/index.js:40:23)
    at loadPlugin (/usr/local/lib/node_modules/[4msemantic-release[24m/lib/plugins/utils.js:51:36)
    at /usr/local/lib/node_modules/[4msemantic-release[24m/lib/plugins/index.js:17:37
    at Array.reduce (<anonymous>)
    at module.exports (/usr/local/lib/node_modules/[4msemantic-release[24m/lib/plugins/index.js:14:34)
    at module.exports (/usr/local/lib/node_modules/[4msemantic-release[24m/lib/get-config.js:84:35)
    at async module.exports (/usr/local/lib/node_modules/[4msemantic-release[24m/index.js:265:32)
    at async module.exports (/usr/local/lib/node_modules/[4msemantic-release[24m/cli.js:55:5) {
  code: [32m'ERR_REQUIRE_ESM'[39m
}
```

**Comment by BrycensRanch** [comment]
why would they make the package esm when they know the pkg is ran in a environment that isn't esm friendly

**Comment by nitzano** [comment]
Soon I'll migrate the plugin to ESM as well as part of #148 since semantic-release was indeed moved to be ESM-only

**Comment by nitzano** [comment]
Should be solved as part of v2+ versions:

https://github.com/nitzano/semantic-release-github-milestones/releases/tag/v2.0.0
